name: Multi-Arch Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        arch: [ x64, arm64 ]

    outputs:
      artifacts: ${{ steps.artifacts.outputs.artifacts }}

    steps:
#      - name: Set Up QEMU (for ARM64 emulation)
#        if: matrix.arch == 'arm64'
#        uses: docker/setup-qemu-action@v3
#        with:
#          platforms: arm64

      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, intl

      - name: Install Composer
        run: |
          curl -sS https://getcomposer.org/installer -o composer-setup.php
          EXPECTED_SIGNATURE="$(curl -sS https://composer.github.io/installer.sig)"
          ACTUAL_SIGNATURE="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
          if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]; then
            echo "ERROR: Invalid installer signature"
            rm composer-setup.php
            exit 1
          fi
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          rm composer-setup.php

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: crazywhalecc/static-php-cli
          ref: main
          path: static-php-cli

      - name: Install Dependencies
        run: cd static-php-cli && composer install

      - name: Build Static PHP
        run: |
          cd static-php-cli
          bin/spc download --with-php=8.2 --for-extensions "apcu,bcmath,calendar,ctype,curl,dba,dom,exif,fileinfo,filter,ftp,gd,iconv,intl,mbregex,mbstring,mysqli,mysqlnd,opcache,openssl,pcntl,pdo,pdo_mysql,pdo_pgsql,pdo_sqlite,pgsql,phar,posix,readline,session,simplexml,sockets,sodium,sqlite3,tokenizer,xml,xmlreader,xmlwriter,xsl,zip,zlib"
          bin/spc doctor --auto-fix
          bin/spc build --build-cli "apcu,bcmath,calendar,ctype,curl,dba,dom,exif,fileinfo,filter,ftp,gd,iconv,intl,mbregex,mbstring,mysqli,mysqlnd,opcache,openssl,pcntl,pdo,pdo_mysql,pdo_pgsql,pdo_sqlite,pgsql,phar,posix,readline,session,simplexml,sockets,sodium,sqlite3,tokenizer,xml,xmlreader,xmlwriter,xsl,zip,zlib" -I "pcre.jit=0"

      - name: Clean Files
        run: |
          cp /home/runner/work/virtiz-bin/virtiz-bin/static-php-cli/buildroot/bin/php /home/runner/work/virtiz-bin/virtiz-bin/php-${{ matrix.arch }}
          rm -rf /home/runner/work/virtiz-bin/virtiz-bin/static-php-cli
          ls -la /home/runner/work/virtiz-bin/virtiz-bin

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: php-${{ matrix.arch }}

  post-run:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    needs: build

    if: always()

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts

      - name: Push Binaries
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Build static-php binaries