name: Multi-Arch Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    strategy:
      matrix:
        os: [ ubuntu-latest-arm64 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up QEMU (for ARM64 emulation)
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name mybuilder --use
          docker buildx inspect --bootstrap

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, intl

      - name: Install composer
        run: |
          curl -sS https://getcomposer.org/installer -o composer-setup.php
          EXPECTED_SIGNATURE="$(curl -sS https://composer.github.io/installer.sig)"
          ACTUAL_SIGNATURE="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
          if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]; then
            echo "ERROR: Invalid installer signature"
            rm composer-setup.php
            exit 1
          fi
          php composer-setup.php --install-dir=/usr/local/bin --filename=composer
          rm composer-setup.php

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: crazywhalecc/static-php-cli
          ref: main
          path: static-php-cli

      - name: Install dependencies
        run: cd static-php-cli && composer install

      - name: Build static PHP
        run: |
          cd static-php-cli
          bin/spc download --with-php=8.2 --for-extensions "apcu,bcmath,calendar,ctype,curl,dba,dom,exif,fileinfo,filter,ftp,gd,iconv,intl,mbregex,mbstring,mysqli,mysqlnd,opcache,openssl,pcntl,pdo,pdo_mysql,pdo_pgsql,pdo_sqlite,pgsql,phar,posix,readline,redis,session,simplexml,sockets,sodium,sqlite3,tokenizer,xml,xmlreader,xmlwriter,xsl,zip,zlib"
          bin/spc doctor --auto-fix
          bin/spc build --build-cli "apcu,bcmath,calendar,ctype,curl,dba,dom,exif,fileinfo,filter,ftp,gd,iconv,intl,mbregex,mbstring,mysqli,mysqlnd,opcache,openssl,pcntl,pdo,pdo_mysql,pdo_pgsql,pdo_sqlite,pgsql,phar,posix,readline,redis,session,simplexml,sockets,sodium,sqlite3,tokenizer,xml,xmlreader,xmlwriter,xsl,zip,zlib" -I "pcre.jit=0"

      - name: Copy files
        run: |
          mkdir -p /home/runner/work/virtiz-bin/virtiz-bin/php
          rm -f /home/runner/work/virtiz-bin/virtiz-bin/php/arm64
          cp /home/runner/work/virtiz-bin/virtiz-bin/static-php-cli/buildroot/bin/php /home/runner/work/virtiz-bin/virtiz-bin/php/arm64
          rm -rf /home/runner/work/virtiz-bin/virtiz-bin/static-php-cli

      - name: Pull remote changes
        run: git pull

      - name: Auto commit binary
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Build static-php arm64 binary
