name: CI on arm linux

on:
  workflow_dispatch:
    inputs:
      operating-system:
        required: true
        description: Compile target arch (Linux only)
        type: choice
        options:
          - aarch64
      version:
        required: true
        description: php version to compile
        default: '8.2'
        type: choice
        options:
          - '8.2'
          - '8.1'
          - '8.0'
          - '7.4'
      build-cli:
        description: build cli binary
        default: true
        type: boolean
      extensions:
        description: extensions to compile (comma separated)
        required: true
        type: string

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: build ${{ inputs.version }} on ${{ inputs.operating-system }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Cache downloaded source
      - id: cache-download
        uses: actions/cache@v3
        with:
          path: downloads
          key: php-${{ inputs.version }}-dependencies-${{ inputs.extensions }}

      # If there's no dependencies cache, fetch sources, with or without debug
      - if: steps.cache-download.outputs.cache-hit != 'true'
        run: SPC_USE_ARCH=${{ inputs.operating-system }} ./scripts/spc-alpine-docker download --with-php=${{ inputs.version }} --for-extensions=${{ inputs.extensions }}

      # Run build command
      - run: SPC_USE_ARCH=${{ inputs.operating-system }} ./scripts/spc-alpine-docker build ${{ inputs.extensions }} --build-cli ${{ env.SPC_BUILD_MICRO }} ${{ env.SPC_BUILD_FPM }}

      # Upload cli executable
      - uses: actions/upload-artifact@v3
        with:
          name: php-${{ inputs.version }}-linux-${{ inputs.operating-system }}
          path: buildroot/bin/php