name: CI on arm linux

on:
  workflow_dispatch:
    inputs:
      operating-system:
        required: true
        description: Compile target arch (Linux only)
        type: choice
        options:
          - aarch64

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: build 8.2 on ${{ inputs.operating-system }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: chmod +x ./scripts/spc-alpine-docker
      - run: SPC_USE_ARCH=${{ inputs.operating-system }} ./scripts/spc-alpine-docker download --with-php=8.2 --for-extensions="apcu,bcmath,calendar,ctype,curl,dba,dom,exif,fileinfo,filter,ftp,gd,iconv,intl,mbregex,mbstring,mysqli,mysqlnd,opcache,openssl,pcntl,pdo,pdo_mysql,pdo_pgsql,pdo_sqlite,pgsql,phar,posix,readline,redis,session,simplexml,sockets,sodium,sqlite3,tokenizer,xml,xmlreader,xmlwriter,xsl,zip,zlib"
      - run: SPC_USE_ARCH=${{ inputs.operating-system }} ./scripts/spc-alpine-docker build "apcu,bcmath,calendar,ctype,curl,dba,dom,exif,fileinfo,filter,ftp,gd,iconv,intl,mbregex,mbstring,mysqli,mysqlnd,opcache,openssl,pcntl,pdo,pdo_mysql,pdo_pgsql,pdo_sqlite,pgsql,phar,posix,readline,redis,session,simplexml,sockets,sodium,sqlite3,tokenizer,xml,xmlreader,xmlwriter,xsl,zip,zlib" --build-cli

      - uses: actions/upload-artifact@v3
        with:
          name: php-8.2-linux-${{ inputs.operating-system }}
          path: bin/php